# Generation Module Configuration
# Settings for all text generation components: Ollama, prompt templates, response parsing

[ollama]
# Ollama server settings
host = "http://localhost"
port = 11434
timeout = 120.0
max_retries = 3

# Model configuration
primary_model = "jobautomation/openeurollm-croatian:latest"
fallback_model = "llama3.2:3b"
embedding_model = "nomic-embed-text"

# Generation parameters
stream = true
temperature = 0.7
max_tokens = 2000
top_p = 0.9
top_k = 64

# Croatian-specific Ollama settings
preserve_diacritics = true
cultural_context = true

[prompts]
# General prompt settings
chunk_header_template = "[Dokument {index}]"
context_separator = "\n\n"
max_context_chunks = 5

# Error messages
no_context_available = "Ne mogu pronaći tu informaciju u dostupnim dokumentima."
generation_error_prefix = "Greška u generiranju odgovora"

# Query type detection keywords
[prompts.keywords]
summary = ["sažetak", "sažmi", "ukratko", "glavne točke", "resume", "pregled"]
comparison = ["usporedi", "razlika", "sličnost", "vs", "nasuprot", "razlikuje", "bolje"]
explanation = ["objasni", "što je", "kako", "zašto", "definiraj", "opiši"]
factual = ["kada", "gdje", "tko", "koliko", "koji", "koja", "ime", "broj"]
cultural = [
    "povijest", "kultura", "tradicija", "umjetnost", "književnost",
    "zagreb", "dubrovnik", "split", "pula", "rijeka", "osijek",
    "jadran", "dalmacija", "slavonija", "istra", "hrvatsko primorje",
    "biser jadrana", "plitvi", "krka", "mljet", "brač", "hvar",
    "franjo tuđman", "ante starčević", "josip jelačić", "miroslav krleža"
]
tourism = [
    "turizam", "odmorište", "plaža", "hotel", "restoran", "znamenitost",
    "posjetiti", "vidjeti", "doći", "putovanje", "odmor", "ljetovanje",
    "nacionalni park", "unesco", "baština"
]

[response_parsing]
# Response parsing and validation settings
min_response_length = 10
max_response_length = 5000
confidence_threshold = 0.3

# Quality indicators
positive_quality_indicators = ["jasno", "sigurno", "točno", "definitivno"]
negative_quality_indicators = ["možda", "vjerojatno", "ne znam sigurno"]

# No answer detection patterns
no_answer_patterns = [
    "ne mogu pronaći", "nije dostupno", "nema informacija",
    "ne znam", "nije jasno", "nedostaju podaci"
]

# Source reference patterns
source_patterns = [
    "\\[dokument \\d+\\]", "prema dokumentu", "u tekstu se navodi", "dokument spominje"
]

# Confidence level indicators
[response_parsing.confidence_indicators]
high = ["jasno je da", "definitvno", "sigurno", "bez sumnje", "očigledno"]
medium = ["vjerovatno", "moguće je", "čini se", "indicira", "sugerira"]
low = ["možda", "nije sigurno", "teško je reći", "nedovoljno informacija", "ograničeno"]

# Text cleaning patterns
[response_parsing.cleaning]
prefixes_to_remove = ["^(odgovor|answer):\\s*", "^(rezultat|result):\\s*", "^(zaključak|conclusion):\\s*"]

# Language detection
[response_parsing.language_detection]
croatian_chars = "čćšžđČĆŠŽĐ"
croatian_words = ["je", "se", "na", "za", "da", "su", "ili", "ako", "kad", "što", "biti", "imati", "moći", "htjeti", "trebati"]
english_words = ["the", "and", "or", "but", "with"]

# Display formatting
[response_parsing.display]
high_confidence_label = "visoka pouzdanost"
medium_confidence_label = "umjerena pouzdanost"
low_confidence_label = "niska pouzdanost"
sources_prefix = "Izvori"
no_answer_message = "Žao mi je, nisam mogao generirati odgovor."
