# Retrieval Configuration
# Settings for query processing, ranking, and retrieval strategies

[query_processing]
# Basic query processing settings
language = "hr"
expand_synonyms = true
normalize_case = true
remove_stop_words = true
min_query_length = 3
max_expanded_terms = 10
enable_spell_check = false

[query_processing.croatian_stop_words]
# Croatian stop words for query filtering
basic = [
    "i", "u", "na", "za", "se", "je", "da", "su", "od", "do", "po", "sa",
    "te", "ta", "to", "ti", "tu", "iz", "ni", "li", "ga", "mu", "pa", "ne",
    "si", "me", "mi", "ih", "im", "ju", "jo", "ja", "ma", "ah", "oh", "al"
]

[retrieval]
# General retrieval settings
default_strategy = "hybrid"
top_k = 10
similarity_threshold = 0.3
fallback_enabled = true
max_retries = 3

[retrieval.strategies]
# Available retrieval strategies
semantic_weight = 0.7
keyword_weight = 0.3
hybrid_fallback = "semantic"

[ranking]
# Document ranking and scoring
method = "croatian"
enable_diversity = true
diversity_threshold = 0.8
boost_recent = true
boost_authoritative = true
content_length_factor = true
keyword_density_factor = true
croatian_specific_boost = true
boost_exact_match = 1.5
boost_title_match = 1.3
boost_metadata_match = 1.2
decay_factor = 0.95

[ranking.weights]
# Ranking component weights
content_weight = 0.6
title_weight = 0.2
metadata_weight = 0.1
freshness_weight = 0.1

[reranking]
# Cross-encoder reranking settings
enabled = true
model_name = "cross-encoder/ms-marco-MiniLM-L-6-v2"
device = "cpu"
batch_size = 4
top_k_for_rerank = 20
confidence_threshold = 0.5

[hybrid_retrieval]
# Hybrid retrieval specific settings
dense_weight = 0.7
sparse_weight = 0.3
fusion_method = "rrf"  # reciprocal rank fusion
rrf_k = 60
normalize_scores = true
