repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # CHECK-ONLY hooks to avoid file modifications during commit
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
        exclude: ^notebooks/.*\.ipynb$
      # DISABLED: These hooks modify files during commit
      # - id: trailing-whitespace
      # - id: end-of-file-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: [--no-fix, --config=services/rag-service/pyproject.toml]  # CHECK-ONLY: Use explicit config
        # WHITELIST: Only process core src subdirectories (same as format_code.py)
        files: ^services/rag-service/src/(utils|generation|preprocessing|retrieval|models|pipeline|vectordb)/.*\.py$
      - id: ruff-format
        args: [--check, --config=services/rag-service/pyproject.toml]  # CHECK-ONLY: Use explicit config
        # WHITELIST: Only process core src subdirectories (same as format_code.py)
        files: ^services/rag-service/src/(utils|generation|preprocessing|retrieval|models|pipeline|vectordb)/.*\.py$

# MyPy disabled in pre-commit to avoid false positives
# Use format_code.py for comprehensive type checking
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.7.0
#    hooks:
#      - id: mypy
#        additional_dependencies: [types-requests, types-PyYAML, types-toml]
#        args: [--no-error-summary]  # Reduce verbose output
#        # WHITELIST: Only process core src subdirectories (same as format_code.py and pyproject.toml)
#        files: ^services/rag-service/src/(utils|generation|preprocessing|retrieval|models|pipeline|vectordb)/.*\.py$
