repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
        exclude: ^notebooks/.*\.ipynb$

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^scripts/.*\.py$
      # Disabled ruff-format to avoid conflict with Black
      # - id: ruff-format
      #   exclude: ^scripts/.*\.py$

  # Temporarily disabled due to 195 type errors - TODO: Re-enable after type fixes
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.7.0
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-PyYAML, types-toml]
  #       exclude: ^(tests/|notebooks/|.*test.*\.py$)
