claude:
  model: "claude-3-sonnet-20240229"
  max_tokens: 1500
  temperature: 0.1
  batch_processing:
    enabled: true
    batch_size: 10
    max_concurrent: 5

prompts:
  system_prompt: |
    You are an expert assistant helping with questions about Croatian documents.
    Use the provided context to answer questions accurately and in Croatian when appropriate.
    If the context doesn't contain relevant information, say so clearly.

  rag_template: |
    Context: {context}

    Question: {question}

    Please provide a clear and accurate answer based on the context above.
