chunking:
  strategies:
    semantic:
      max_chunk_size: 512
      overlap: 50
      respect_sentences: true
    fixed:
      max_chunk_size: 1024
      overlap: 100
    paragraph:
      preserve_structure: true
      min_chunk_size: 100

croatian_specific:
  sentence_endings: [".", "!", "?", "…"]
  preserve_quotes: true
  handle_dialogue: true
