embedding:
  model_name: "paraphrase-multilingual-MiniLM-L12-v2"
  device: "cpu"
  normalize_embeddings: true
  batch_size: 32

croatian_processing:
  preserve_diacritics: true
  normalize_spaces: true
  handle_encoding: "utf-8"
  sentence_splitter: "spacy"
